puppetlabs/jruby-utils

README.md

Correct spelling of "maintenance". Change where maintenance section says to
file tickets to TK, which matches the "support" section. TK seems more
appropriate than SERVER since this is not a Puppet Server specific library.

(maint) Update maintenance section of README

---

src/clj/puppetlabs/services/jruby/jruby_agents.clj
src/clj/puppetlabs/services/jruby/jruby_core.clj
src/clj/puppetlabs/services/jruby/jruby_internal.clj
src/clj/puppetlabs/services/jruby/jruby_schemas.clj
src/clj/puppetlabs/services/jruby/jruby_service.clj
test/integration/puppetlabs/services/jruby/jruby_internal_test.clj
test/integration/puppetlabs/services/jruby/jruby_locking_test.clj
test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
test/unit/puppetlabs/services/jruby/jruby_agents_test.clj
test/unit/puppetlabs/services/jruby/jruby_core_test.clj
test/unit/puppetlabs/services/jruby/jruby_interpreter_test.clj
test/unit/puppetlabs/services/jruby/jruby_pool_test.clj
test/unit/puppetlabs/services/jruby/jruby_service_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

Add a lifecycle map to the jruby config that includes hooks for initialization, initialization of environment variables, shutdown, and shutdown-on-error that get called in the appropriate places. Users of this
library will then be able to add their own custom initialization and cleanup logic via this map.

(TK-367) Add initialization and cleanup hooks

---

test/unit/puppetlabs/jruby_utils/lockable_pool_test.clj

This commit adds some logic to the
pool-lock-supersedes-existing-borrows-test to try to wait until
.isLocked() returns true for a requested lock until the test moves on to
validating that borrow requests are held off by the lock.  Without this
change, it was more likely (although still somewhat rare) for the test
to return instances to the pool before the .lock() request was even
made, leading to borrow requests being granted immediately rather than
being held off by the lock.  Test assertions would fail as a result.
This was cherry-picked from https://github.com/puppetlabs/puppetserver/pull/1104.

(SERVER-1375) Adds a pool lock check to pool-lock-supersedes test

---

src/clj/puppetlabs/services/jruby/jruby_agents.clj
src/clj/puppetlabs/services/jruby/jruby_core.clj
src/clj/puppetlabs/services/jruby/jruby_internal.clj
src/clj/puppetlabs/services/jruby/jruby_schemas.clj
test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
test/unit/puppetlabs/services/jruby/jruby_pool_test.clj

Previously, the `max-requests` setting was used to determine if/when to flush
a JRuby instance after it had handled a certain number of requests in Puppet
Server. This logic might be useful to other users of this library (not just
Puppet Server), but such users might not actually have "requests" causing
JRubyInstances to be used. This commit renames `max-requests` (the setting and
all internal references) to `max-borrows`, which better reflects what it
actually does.

(TK-377) Rename 'max-requests' to 'max-borrows'

---

src/clj/puppetlabs/services/jruby/jruby_agents.clj
src/clj/puppetlabs/services/jruby/jruby_core.clj
src/clj/puppetlabs/services/jruby/jruby_internal.clj
src/clj/puppetlabs/services/jruby/jruby_schemas.clj
test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
test/unit/puppetlabs/services/jruby/jruby_agents_test.clj
test/unit/puppetlabs/services/jruby/jruby_pool_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

Both the pool context and the instance contain keys that we don't want users
to mess with - such as the pool and flush agents and the `flush-instance-fn`.
This commit moves all keys we want to keep "private" in both the pool context
and the instance underneath an `:internal` key.
For the the pool context, the `:config` key remains public; for the instance,
the `:id` and `:scripting-container` remain public.

(TK-376) Add :internal key to pool context and instance

---

project.clj
src/clj/puppetlabs/services/jruby/jruby_core.clj
test/integration/puppetlabs/services/jruby/jruby_pool_int_test.clj
test/unit/puppetlabs/services/jruby/jruby_agents_test.clj
test/unit/puppetlabs/services/jruby/jruby_testutils.clj

Use ringutils middleware to throw a service unavailable error, and standardize
on `:kind` and `:msg` for error keys.
Also bump some dependency versions.

(maint) Use ringutils

---

src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_schemas.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_interpreter_test.clj

This PR adds a whitelisting capability to the handling of environment variables. This also adds an `environment-vars` key to the list of accepted keys in JRubyConfig so that this key can be used in a `puppetserver.conf` file. Keys that are added to the new `environment-vars` map will be reachable and visible by any Ruby code. This PR also adds tests to make sure that the environment variables are correctly stored and visible.

(SERVER-584) improve handling of environment vars

---

project.clj
test/integration/puppetlabs/services/jruby_pool_manager/jruby_pool_int_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_interpreter_test.clj

This commit updates us to use a PL release of JRuby 1.7.26 that has
been deployed to clojars, as
there are upstream fixes that we really need and it's not clear
when they might be doing their own release.
The commit also updates a few tests, because recent changes in
JRuby introduce a 'RUBY' environment variable into all
ScriptingContainers.

(SERVER-1408) Update to PL release of JRuby 1.7.26

---

project.clj

This commit updates the PL JRuby stdlib dependency to 1.7.26-pl-rc1.

(SERVER-1408) Update PL JRuby stdlib to 1.7.26-pl-rc1

---

project.clj

This commit bumps the JRuby dependencies to upstream version 1.7.26.

(MAINT) Bump to upstream JRuby 1.7.26

---

CHANGELOG.md

This commit adds release notes to the CHANGELOG.md file for the 0.2.1
release.

(MAINT) Add CHANGELOG.md release notes for 0.2.1 release

---

test/unit/puppetlabs/services/jruby_pool_manager/jruby_agents_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_testutils.clj

This commit adds a borrow to the main service pool in the
`with-jruby-retry-test-via-mock-get-pool` function before any borrows
with intentional retries are attempted.  Previously, without the extra
borrow, the test's use of the `with-redefs` function to switch out the
`get-pool` function could cause pool instances to only be created in
the retry pool and not the main service pool, leading a borrow attempt
made against the main service pool to hang.

(TK-398) Fix with-jruby-retry-test race condition

---

src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_schemas.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_interpreter_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_pool_test.clj

This commit adds support for a `gem-path` configuration setting.
If specified it will be used as the value for the GEM_PATH
environment variable.  If not, GEM_PATH will be set to the same value
as GEM_HOME.
This is in support of SERVER-1412, where the server will pass in a value for this setting that includes a new "vendored" gem directory.  My intent is that Puppet Server will *always* pass in a value for this setting, and will have its own logic for defaulting the value that it uses for that setting.  But as far as the API of this library goes it seemed like this was the best way to build it.  Open to feedback - would be willing to make it a required argument if people thought that was better (that was my original instinct on how to implement this).

(SERVER-1412) Add support for `gem-path` config

---

src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_schemas.clj
test/integration/puppetlabs/services/jruby_pool_manager/jruby_internal_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_pool_test.clj

Add a `compat-version` JRuby setting to allow configuration of the
compatibility version. The valid options are 1.9 or 2.0. This is tolerated as
a string or a double (so we don't need to worry about conversions between
Hiera/NC and HOCON parsing). The default is 1.9.

(SERVER-1585) Add `compat-version` setting

---

CHANGELOG.md
project.clj

This commit adds a release note and bumps the project.clj version in
support of an 0.4.0 release.

(MAINT) Prep for 0.4.0 release

---

src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj
src/java/com/puppetlabs/jruby_utils/jruby/InternalScriptingContainer.java
src/java/com/puppetlabs/jruby_utils/jruby/ScriptingContainer.java

This commit extracts an interface for use with schema/type validation
with ScriptingContainers.  This helps establish the baseline methods
that external consumers of the library can expect to be present for any
ScriptingContainers that the library creates for them.  The interface
is named ScriptingContainer.  The corresponding implementation class is
renamed to InternalScriptingContainer.

(SERVER-797) Extract an interface for ScriptingContainer

---

CHANGELOG.md

This commit adds a section to the CHANGELOG.md for the upcoming 0.4.1
release.

(MAINT) Prep CHANGELOG for 0.4.1 release

---

CHANGELOG.md
src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_schemas.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_interpreter_test.clj

jruby-utils limits the environment variables that it passes through to the
jruby interpreters. Previously, the list of environment variables allowed to
pass through did not include any proxy-related variables. This was a problem
because in some environments these variables are necessary for installing
gems, and rubygems respects these variables.
This commit adds the environment variables `HTTP_PROXY`, `http_proxy`,
`HTTPS_PROXY`, `https_proxy`, `NO_PROXY`, and `no_proxy` to be passed through
to the jruby scripting container.
In most cases developer workstations and CI systems won't have these variables
set, and there is no good way (without adding additional libraries and doing
some amount of hackery) to mock them out for tests. Thus, no tests have been
added or modified to test this …

(SERVER-377) Allow proxy environment variables to pass through

---

project.clj
src/java/com/puppetlabs/jruby_utils/jruby/Slf4jLogger.java
test/unit/puppetlabs/jruby_utils/slj4j_logger_test.clj

This commit adds a class, Slf4jLogger, which implements the JRuby Logger
interface, forwarding any logging calls which are received on to an
slf4j logger.  This class doesn't actually hook up the logger to created
JRuby instances since JRuby classes typically get the object that they
use for logging during static initialization, which would most likely
complete before any attempt to set a custom logger with JRuby could be
done.  Use of this Logger would typically require that the consuming
process set the jruby.logger.class Java system property to the namespace
of the new class on the command line, e.g.,
-Djruby.logger.class=com.puppetlabs.jruby_utils.jruby.Slf4jLogger.

(SERVER-1475) Add an JRuby slf4j Logger adapter

---

CHANGELOG.md
project.clj

This commit bumps the project.clj version to 0.6.0-SNAPSHOT and adds
notes to the CHANGELOG.md for the upcoming 0.6.0 release.

(MAINT) Prep for 0.6.0 release

---

CHANGELOG.md
project.clj

This is a bugfix and internal improvement release.
* Remove the need for a second `JrubyPool` during pool flushes to improve
system stability
* Fix possibility of race condition where the pool lock can be granted even
when some jruby instances are still doing work

(MAINT) Bump version for 0.7.0 release

---

src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_agents.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_schemas.clj
src/java/com/puppetlabs/jruby_utils/pool/JRubyPool.java
src/java/com/puppetlabs/jruby_utils/pool/LockablePool.java
test/unit/puppetlabs/jruby_utils/lockable_pool_test.clj

This PR modifies the pool flush code to use a lock timeout.
It also adds a new config setting to specify the timeout.
---
This PR goes along with https://github.com/puppetlabs/puppetserver/pull/1330

Server 1704 introduce pool lock timeout

---

src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
test/integration/puppetlabs/services/jruby_pool_manager/jruby_locking_test.clj

This commit adds a macro, `with-lock-with-timout`, which is identical to
`with-lock`, except that it accepts a timeout parameter specified in milliseconds
If the timeout is exceeded, a `TimeoutException` will be thrown and the pool
will remain unlocked

(SERVER-1704) Add with-lock-with-timeout macro

---

CHANGELOG.md
project.clj

This is a minor feature and bugfix release.
* Introduce `:flush-timeout` config setting to specify how long a pool flush
attempt will wait for jruby instances to be returned to the pool before
aborting the attempt
* Add `lockWithTimeout` method to the `JrubyPool` class to facilitate the new
`:flush-timeout` setting

(MAINT) Update changelog and version for 0.8.0 release

---

README.md
ext/travisci/test.sh
project.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_schemas.clj
src/java/com/puppetlabs/jruby_utils/jruby/InternalScriptingContainer.java
test/integration/puppetlabs/services/jruby_pool_manager/jruby_internal_test.clj
test/integration/puppetlabs/services/jruby_pool_manager/jruby_locking_test.clj
test/integration/puppetlabs/services/jruby_pool_manager/jruby_pool_int_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_agents_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_core_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_interpreter_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_pool_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_schemas_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_service_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_testutils.clj

This PR adds support for exercising JRuby 9k in jruby-utils.  The default
jruby-utils dependencies still pull in dependencies from JRuby 1.7.x.  When
an alternate leiningen profile, jruby9k, is exercised when `lein test` is run,
however, jruby9k-related dependencies are pulled in instead of JRuby
1.7.x-related ones.
This PR also includes some code specific to how jruby-utils is exercised
when running with JRuby 9k, including:
* Emit a warning if the `compat-version` setting is set.  JRuby 9k has a
hardcoded `compat-version` set internally and, so, it cannot be
overridden at run-time.
* Code for cleaning up temporary jars and jar files which are currently
being leaked by JRuby when a ScriptingContainer is terminated.  See
SERVER-1777 for more details on pursuing a longer-term fix for this …

(SERVER-1630) Add support for exercising JRuby 9k

---

ext/travisci/test.sh

This commit changes the use of lein2 to lein in the Travis script.  This
is being done to make the job usable for both Jenkins and Travis CI
runs.

(SERVER-1630) Use lein instead of lein2 for Travis script

---

src/java/com/puppetlabs/jruby_utils/jruby/InternalScriptingContainer.java

Previously, a warning would be generated each time the JRuby
InternalScriptingContainer would fail to remove a file during its
termination.  Per work in the upstream JRuby project that we hope
will land soon, https://github.com/jruby/jruby/pull/4578, a JRuby
shutdown hook could remove some of these files before the
InternalScriptingContainer has a chance to remove them.  This commit
removes the warnings to avoid creating unnecessary noise in the logs
related to the timing of file deletions.

(MAINT) Remove warning for jar deletion failure

---

project.clj

This commit bumps the jruby-deps version dependencies from 1.7.26-1 to
1.7.26-2 and from 9.1.8.0-1 to 9.1.9.0-1.

(SERVER-1815) Bump jruby-deps versions to 1.7.26-2 and 9.1.9.0-1

---

project.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_schemas.clj
test/integration/puppetlabs/services/jruby_pool_manager/jruby_internal_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_core_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_pool_test.clj

This PR bumps the jruby-deps dependency for 1.7 from 1.7.26-2 to
1.7.27-1.
This PR removes support for the compat-version setting from
jruby-utils.  The compat-version setting was introduced in jruby-utils
version 0.4.0 to allow for JRuby 1.7 to optionally run under Ruby
language version 2.0 instead of the default version, 1.9.  JRuby
1.7.27 effectively breaks the ability to use Ruby language version
2.0, however, due to a regression - see:
https://github.com/jruby/jruby/issues/4613 - and is unlikely to be
fixed in the future.  JRuby 9k also does not support compat-version
configurability.  Now that jruby-utils can be used with
JRuby 9k for Ruby language 2+ support, it is no longer valuable to be
able to set compat-version to 2 for use with JRuby 1.7. 
This PR also adds a helper method, …

(SERVER-1661) Bump JRuby to 1.7.27 and remove compat-version configurability

---

project.clj

This commit bumps the jruby-deps for 9k from 9.1.9.0-1 to 9.1.9.0-2.
This transitively pins to newer versions of jffi and jnr-ffi, 1.2.16 and
2.1.6, which have a fix for leaks around native memory allocations.  See
https://github.com/jnr/jnr-ffi/issues/117.

(SERVER-1821) Bump JRuby 9k dep to 9.1.9.0-2 for ffi memory leak fix

---

project.clj

This commit bumps jruby-utils' JRuby 9k test dependency to jruby-deps
9.1.11.0-1.

(SERVER-1840) Bump to JRuby 9.1.11.0-1

---

project.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_core_test.clj

This commit updates the jruby version for the jruby9k profile to
9.1.15.0, which is the latest as of now. jruby 9.1.15.0 has a
jruby-readline change which has impacted how we pass strings to IRB in
tests. They now require a newline in order to be executed as expected.

(SERVER-1874) Update to jruby 9.1.15.0

---

src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj
test/integration/puppetlabs/services/jruby_pool_manager/jruby_internal_test.clj

Previously when profiler-output-file was set, it would be the same for
each jruby in the pool, which is undesireable. This commit adds hashCode
to the filename to ensure that they are unique across jrubies.

(SERVER-1780) Insert hashCode into profiler file name

---

src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_agents.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_schemas.clj
test/integration/puppetlabs/services/jruby_pool_manager/jruby_pool_int_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_pool_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_testutils.clj

Previously all JRuby instances would be flushed after they reached
`max-requests-per-instance`. This could cause a thundering herd of
JRuby instance initialization which we've observed during
performance testing.
This patch creates a `splay-instance-flush` configuration option
(available via code for testing but not intended to be plumbed through
to the user). If this is true (the default value) when we first
initialize a JRuby Pool and fill it with instances each instance
receives an `initial-borrows` value that is a fraction of the
max-requests. If set, the `return-to-pool` method will prefer the
value of initial-borrows to that of max-requests to determine if
the instance should be flushed. Subsequent instance creations wil not
receive an initial-borrows value unless the entire pool is …

(SERVER-2060) Splay JRuby instance flushing

---

src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj

This commit adds a function that can configure the KCode, external
encoding, and source encoding of the JRuby scripting containers. We use
this function when initializing our JRuby instances to set these
encodings to UTF-8, to avoid parsing source files as US-ASCII, which can
cause issues with translation interpolation.
Note that this is only relevant in JRuby 1.7; in JRuby 9K, source files are parsed
as UTF-8 by default.

(PUP-8226) Set JRuby KCode, source encoding, and external encoding

---

src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
test/integration/puppetlabs/services/jruby_pool_manager/jruby_internal_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_core_test.clj

In jruby 9k, to get comparable performance to 1.7, jit must be enabled
for compile-mode. This commit updates the default compile mode for jruby
to be jit when the version is 9k, but maintains the old default of off
for jruby 1.7.

(SERVER-2130) Update default compile-mode to jit for jruby9k

---

src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_agents.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj

This commit swaps formatting log methods such as `log/infof` for their
unformatted counterparts: `log/info`. This is done in cases where the
log method is receiving a value generated by `i18n`. The `i18n` methods
perform formatting, which renders the additional formatting done by
`log` redundant and potentially dangerous as any translation that
generates a sequence of characters that looks like a format statement
will cause an exception to be raised.

(maint) Remove redundant formatting from logging

---

project.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
test/integration/puppetlabs/services/jruby_pool_manager/jruby_internal_test.clj

This commit adds a `get-jruby-thread-dump` method that iterates through
the interpreters registered to a JRuby pool and returns a Ruby backtrace
from each one. Generation of the backtraces is done via the JRuby JMX
management interface and thus requires `-Djruby.management.enabled=true`
to be set in JAVA_ARGS.

(SERVER-2193) Add API for retrieving JRuby thread dumps

---

CHANGELOG.md
project.clj

nb. the clj-parent bump wasn't required for 9.2.9.0 but accurately reflects the dependencies that we expect it to used with.

(maint) Use JRuby 9.2.9.0 & latest clj-parent

---

src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_schemas.clj

This setting will eventually be used to control pool behavior when a
multithreaded environment is requested.

(SERVER-2630) Add `multithreaded` config setting

---

project.clj

Version 9.2.9.0 has an issue when first using the `system` function,
that is preventing us from installing gems under JRuby. This commit
downgrades us back to 9.2.8.0 until that bug is fixed.

(SERVER-2674) Downgrade to JRuby 9.2.8.0

---

project.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/instance_pool.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_agents.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_pool_manager_core.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/reference_pool.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_schemas.clj
src/clj/puppetlabs/services/protocols/jruby_pool.clj
src/java/com/puppetlabs/jruby_utils/pool/JRubyPool.java
src/java/com/puppetlabs/jruby_utils/pool/LockablePool.java
src/java/com/puppetlabs/jruby_utils/pool/ReferencePool.java
test/integration/puppetlabs/services/jruby_pool_manager/jruby_internal_test.clj
test/integration/puppetlabs/services/jruby_pool_manager/jruby_locking_test.clj
test/integration/puppetlabs/services/jruby_pool_manager/jruby_pool_int_test.clj
test/unit/puppetlabs/jruby_utils/lockable_pool_test.clj
test/unit/puppetlabs/jruby_utils/lockable_ref_pool_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_agents_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_pool_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_ref_pool_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_service_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_testutils.clj

This new attempt defines a Clojure protocol for interacting with the JRuby pool. This allows for some polymorphism of higher-level logic around the pool itself, which is particularly important for flushing with `max-requests-per-instance` (which involves the whole pool when using the ReferencePool versus just one instance in the original implementation) and for shutting down. It also allows for cleaner, easier-to-read logic in other places (like pool filling) that differ between the backing implementations.

(SERVER-2529) Clojure Reference Pool

---

src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/java/com/puppetlabs/jruby_utils/pool/JRubyPool.java
src/java/com/puppetlabs/jruby_utils/pool/LockablePool.java
src/java/com/puppetlabs/jruby_utils/pool/ReferencePool.java

This commit adds a method for getting the number of free Jrubies in the pool.
This is the same as `currentSize` for the existing instance pool, but for the
reference pool (multithreaded) this will either be 1 (if nothing is using the
pool) or 0. This ensures that the `num-free-jrubies` metric (which uses
`free-instance-count`) is accurate for both pool types.

(SERVER-2681) Add `availableJrubies` method

---

src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/java/com/puppetlabs/jruby_utils/pool/JRubyPool.java
src/java/com/puppetlabs/jruby_utils/pool/LockablePool.java
src/java/com/puppetlabs/jruby_utils/pool/ReferencePool.java

This reverts commit 1e6c95a34b6eb09d47a55af62e970177c80bcb07.
We decided to overload the `num-free-jrubies` metric to report the number of
free workers in multithreaded mode, so there is no need for a separate
`availableJRubies` method. The `currentSize` can be used.

Revert "(SERVER-2681) Add `availableJrubies` method"

---

src/clj/puppetlabs/services/jruby_pool_manager/impl/instance_pool.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_events.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/reference_pool.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_schemas.clj
src/clj/puppetlabs/services/protocols/jruby_pool.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_pool_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_ref_pool_test.clj

This commit adds a `:worker-id` event field to be sent to the metrics service.
For the instance pool, this is the instance id we've already been using. For
the new reference pool, this is the thread id. This will allow us to reason
about pool usage in similar ways for both pool types.

(SERVER-2715) Record worker-id when borrowing pool resources

---

src/clj/puppetlabs/services/jruby_pool_manager/impl/instance_pool.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/reference_pool.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/clj/puppetlabs/services/protocols/jruby_pool.clj

This commit puts the `instance-returned` callback before the actual `return`
again in the public-facting `return-to-pool` method. Previously, if a request
was waiting for a new instance, calling `return` first could trigger a new
borrow so quickly that the borrow event callback would trigger before the return
event callback. For the instance pool, because instances ids are reused, instead
of 1. removing the instance from the `borrowed-instances` metric and then 2.
adding it back with the new borrow event, we ended up 1. updating the
`borrowed-instances` with the new event and then 2. removing the instance from
`borrowed-instances`, which caused the metric to lose track of a whole instance.

(SERVER-2679) Ensure return callback runs before actual return

---

project.clj

This update contains a fix for a sprintf buffer bug.

(SERVER-2660) Update JRuby to 9.2.11.1

---

project.clj

We discovered a potential bug in JRuby 9.2.11.1 that might be causing
StackOverflow errors that put the server into an unrecoverable state.
We're rolling back JRuby in preparation for a release, to be safe.

(SERVER-2793) Roll back JRuby to 9.2.8.0

---

project.clj

This reverts commit b5ffb91f8bbc27ad83aadedc6e547756218398c4.

(SERVER-2793) Bump JRuby 9.2.11.1 to again

---

src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj

This is on by default as of JRuby 9.2.11.0. It appears to be related to
stack overflows that we've started seeing, so turn it off for now.

(SERVER-2793) Disable invokedynamic for yields

---

project.clj

This is a maintenance update. Newer versions of clj-parent pull in a new
enough snakeyaml that we no longer need to pin it here.

(SERVER-3007) Update Jruby to 9.2.17.0

---

project.clj

This unpins a dependency that was causing pedantic conflicts.

(maint) Bump jruby-deps to 9.3.4.0-2

---

project.clj

Depends on release jruby-deps from https://github.com/puppetlabs/jruby-deps/pull/51 both require https://github.com/puppetlabs/ci-job-configs/pull/9183

(maint) Update jruby 9.3.11

---

project.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_core_test.clj

individual commit messages:
----
c7319f1 (maint) Update clj-parent
The current version of clj-parent is several major versions behind the
version of clj-parent that this version of jruby-utils will be in.
----
cbbab26 (PE-36375) Take up JRuby 9.4.3
When we upgraded to JRuby 9.4 we broke our IRB testing because of an
issue in JRuby and the io/console library. The FFI that io/console
integrates with has changed and the 'path' variable no longer exists on
linux based consoles unless the IO is backed by an actual file.[1]
This fails in our testing where we stub stdin & stdout with essentially
a StringIO object, but does not fail when running IRB normally with an
actual terminal attached.
This should have a known issue written about it, however I know of no
use case where a user would write a …

(PE-36375) Take up JRuby 9.4.3

---

.github/workflows/lein-test.yaml
src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_agents.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_schemas.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_agents_test.clj
test/unit/puppetlabs/services/jruby_pool_manager/jruby_pool_test.clj

This is for PE-37376, which is a product priority for the next release and seemed like a small amount of work and nice break before I moved back to another acceptance testing ticket.

(PE-37376) Parallelize JRuby instance creation

---

src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_agents.clj
src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj
src/clj/puppetlabs/services/jruby_pool_manager/jruby_schemas.clj

Puppet may apply a "settings catalog" when it initializes. This will check the filesystem and create any directories specified by settings that do not already exist. This will cause errors if Puppet does need to create directories and is initialized in parallel. To resolve this when priming the pool we now instantiate one instance first before initializing the remaining instances in parallel.

(PE-37376) Initialize one JRuby instance first when filling a pool
